### ISSUE TITLE
Too many Connections

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-codeception-framework#2]
In large acceptance tests, sometimes the `SQLSTATE[08004] [1040] Too many connections` exception will rise. I couldn't find a better solution than closing the connection within a restricted timeout. 

```yaml
doctrine:
    dbal:
        connections:
            default:
                options:
                    1002: 'SET SESSION wait_timeout=30;'
```

I've a bad feeling about this, we should investigate further, finding a solution to close connections properly.
